name: taggame
description: ZombieTag
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^12.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  built_value: ^8.7.0
  built_collection: ^5.1.1
  rxdart: ^0.27.7
  intl: ^0.18.1
  collection: ^1.17.2
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  flutter_screenutil: ^5.9.0
  lottie: ^2.7.0
  shimmer_animation: ^2.1.0+1
  flutter_vibrate: ^1.3.0
  figma_squircle: ^0.5.3
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.13.0
  another_flushbar: ^1.12.30
  permission_handler: ^11.0.1
  uuid: ^4.2.1
  pedometer: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  built_value_generator: ^8.7.0
  build_runner: ^2.4.6
  go_router_builder: ^2.3.4
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/avatars/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
    - family: SFProText
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
        - asset: fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Text-Semibold.otf
          weight: 600
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500

flutter_gen:
  integrations:
    lottie: true